/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    news: News;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'en' | 'en'[];
  globals: {
    nav: Nav;
    footer: Footer;
    brand: Brand;
  };
  globalsSelect: {
    nav: NavSelect<false> | NavSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    brand: BrandSelect<false> | BrandSelect<true>;
  };
  locale: 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Admins manage users & settings. Editors manage content.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Marketing pages, assembled from blocks. "/" is the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path. Use "home" for the front page.
   */
  slug: string;
  layout?:
    | (
        | HeroBlock
        | StatScorecardBlock
        | StepsBlock
        | MediaPanelsBlock
        | AppShowcaseBlock
        | PodcastBlock
        | ClosingCtaBlock
        | FeatureRowsBlock
        | CalloutBlock
        | FaqBlock
        | LocationsBlock
        | RichTextBlock
      )[]
    | null;
  /**
   * Falls back to the page title.
   */
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrow?: string | null;
  heading: string;
  subheading?: string | null;
  body?: string | null;
  background?: (number | null) | Media;
  video?: (number | null) | Media;
  ctas?:
    | {
        label: string;
        /**
         * Anchor (#how) or URL. Leave blank for a placeholder.
         */
        href?: string | null;
        style?: ('aqua' | 'solid' | 'outline' | 'link') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatScorecardBlock".
 */
export interface StatScorecardBlock {
  theme?: ('navy' | 'paper') | null;
  eyebrow?: string | null;
  heading?: string | null;
  body?: string | null;
  sideImage?: (number | null) | Media;
  stats?:
    | {
        label: string;
        score: number;
        accent?: boolean | null;
        id?: string | null;
      }[]
    | null;
  logoStrip?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statScorecard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock".
 */
export interface StepsBlock {
  theme?: ('navy' | 'paper') | null;
  eyebrow?: string | null;
  heading?: string | null;
  body?: string | null;
  ctas?:
    | {
        label: string;
        /**
         * Anchor (#how) or URL. Leave blank for a placeholder.
         */
        href?: string | null;
        style?: ('aqua' | 'solid' | 'outline' | 'link') | null;
        id?: string | null;
      }[]
    | null;
  steps?:
    | {
        kicker?: string | null;
        title: string;
        body?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'steps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaPanelsBlock".
 */
export interface MediaPanelsBlock {
  theme?: ('navy' | 'paper') | null;
  eyebrow?: string | null;
  heading?: string | null;
  body?: string | null;
  ctas?:
    | {
        label: string;
        /**
         * Anchor (#how) or URL. Leave blank for a placeholder.
         */
        href?: string | null;
        style?: ('aqua' | 'solid' | 'outline' | 'link') | null;
        id?: string | null;
      }[]
    | null;
  panels?:
    | {
        caption?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaPanels';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AppShowcaseBlock".
 */
export interface AppShowcaseBlock {
  eyebrow?: string | null;
  heading?: string | null;
  body?: string | null;
  tags?:
    | {
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  ctas?:
    | {
        label: string;
        /**
         * Anchor (#how) or URL. Leave blank for a placeholder.
         */
        href?: string | null;
        style?: ('aqua' | 'solid' | 'outline' | 'link') | null;
        id?: string | null;
      }[]
    | null;
  phones?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'appShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PodcastBlock".
 */
export interface PodcastBlock {
  heading?: string | null;
  eyebrow?: string | null;
  thumbnail?: (number | null) | Media;
  video?: (number | null) | Media;
  ctas?:
    | {
        label: string;
        /**
         * Anchor (#how) or URL. Leave blank for a placeholder.
         */
        href?: string | null;
        style?: ('aqua' | 'solid' | 'outline' | 'link') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'podcast';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClosingCtaBlock".
 */
export interface ClosingCtaBlock {
  background?: (number | null) | Media;
  heading: string;
  body?: string | null;
  accentLine?: string | null;
  ctas?:
    | {
        label: string;
        /**
         * Anchor (#how) or URL. Leave blank for a placeholder.
         */
        href?: string | null;
        style?: ('aqua' | 'solid' | 'outline' | 'link') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'closingCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureRowsBlock".
 */
export interface FeatureRowsBlock {
  theme?: ('navy' | 'paper') | null;
  eyebrow?: string | null;
  heading?: string | null;
  body?: string | null;
  image?: (number | null) | Media;
  rows?:
    | {
        label?: string | null;
        title?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureRows';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock".
 */
export interface CalloutBlock {
  theme?: ('navy' | 'paper') | null;
  label?: string | null;
  heading?: string | null;
  body?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  theme?: ('navy' | 'paper') | null;
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        q?: string | null;
        a?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocationsBlock".
 */
export interface LocationsBlock {
  eyebrow?: string | null;
  heading?: string | null;
  body?: string | null;
  items?:
    | {
        region?: string | null;
        name?: string | null;
        address?: string | null;
        cta?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'locations';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  theme?: ('navy' | 'paper') | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Events float their date, time & location.
   */
  type?: ('news' | 'event') | null;
  /**
   * Badge, e.g. Partnership, Research, Event
   */
  category?: string | null;
  /**
   * Publication / partner name, e.g. AdventHealth
   */
  source?: string | null;
  date: string;
  /**
   * Event start (date & time)
   */
  startsAt?: string | null;
  /**
   * Event location
   */
  venue?: string | null;
  summary?: string | null;
  /**
   * External article / event link
   */
  url?: string | null;
  image?: (number | null) | Media;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        statScorecard?: T | StatScorecardBlockSelect<T>;
        steps?: T | StepsBlockSelect<T>;
        mediaPanels?: T | MediaPanelsBlockSelect<T>;
        appShowcase?: T | AppShowcaseBlockSelect<T>;
        podcast?: T | PodcastBlockSelect<T>;
        closingCta?: T | ClosingCtaBlockSelect<T>;
        featureRows?: T | FeatureRowsBlockSelect<T>;
        callout?: T | CalloutBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        locations?: T | LocationsBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  body?: T;
  background?: T;
  video?: T;
  ctas?:
    | T
    | {
        label?: T;
        href?: T;
        style?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatScorecardBlock_select".
 */
export interface StatScorecardBlockSelect<T extends boolean = true> {
  theme?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  sideImage?: T;
  stats?:
    | T
    | {
        label?: T;
        score?: T;
        accent?: T;
        id?: T;
      };
  logoStrip?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock_select".
 */
export interface StepsBlockSelect<T extends boolean = true> {
  theme?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  ctas?:
    | T
    | {
        label?: T;
        href?: T;
        style?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        kicker?: T;
        title?: T;
        body?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaPanelsBlock_select".
 */
export interface MediaPanelsBlockSelect<T extends boolean = true> {
  theme?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  ctas?:
    | T
    | {
        label?: T;
        href?: T;
        style?: T;
        id?: T;
      };
  panels?:
    | T
    | {
        caption?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AppShowcaseBlock_select".
 */
export interface AppShowcaseBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  ctas?:
    | T
    | {
        label?: T;
        href?: T;
        style?: T;
        id?: T;
      };
  phones?:
    | T
    | {
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PodcastBlock_select".
 */
export interface PodcastBlockSelect<T extends boolean = true> {
  heading?: T;
  eyebrow?: T;
  thumbnail?: T;
  video?: T;
  ctas?:
    | T
    | {
        label?: T;
        href?: T;
        style?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClosingCtaBlock_select".
 */
export interface ClosingCtaBlockSelect<T extends boolean = true> {
  background?: T;
  heading?: T;
  body?: T;
  accentLine?: T;
  ctas?:
    | T
    | {
        label?: T;
        href?: T;
        style?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureRowsBlock_select".
 */
export interface FeatureRowsBlockSelect<T extends boolean = true> {
  theme?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  image?: T;
  rows?:
    | T
    | {
        label?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock_select".
 */
export interface CalloutBlockSelect<T extends boolean = true> {
  theme?: T;
  label?: T;
  heading?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  theme?: T;
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocationsBlock_select".
 */
export interface LocationsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  items?:
    | T
    | {
        region?: T;
        name?: T;
        address?: T;
        cta?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  theme?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  category?: T;
  source?: T;
  date?: T;
  startsAt?: T;
  venue?: T;
  summary?: T;
  url?: T;
  image?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav".
 */
export interface Nav {
  id: number;
  items?:
    | {
        label: string;
        /**
         * Anchor (#how) or URL.
         */
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  legalNote?: string | null;
  columns?:
    | {
        heading?: string | null;
        links?:
          | {
              label: string;
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand".
 */
export interface Brand {
  id: number;
  name?: string | null;
  tagline?: string | null;
  logoLight?: (number | null) | Media;
  logoDark?: (number | null) | Media;
  colors?:
    | {
        /**
         * e.g. navy, aqua, paper
         */
        token?: string | null;
        /**
         * hex, e.g. #081c26
         */
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. 999px (pill), 14px, 4px
   */
  radius?: string | null;
  /**
   * e.g. Instrument Sans, Fraunces
   */
  headingFont?: string | null;
  bodyFont?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav_select".
 */
export interface NavSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  contactEmail?: T;
  contactPhone?: T;
  legalNote?: T;
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand_select".
 */
export interface BrandSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  logoLight?: T;
  logoDark?: T;
  colors?:
    | T
    | {
        token?: T;
        value?: T;
        id?: T;
      };
  radius?: T;
  headingFont?: T;
  bodyFont?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}